"""Initial migration

Revision ID: 1195506c0e25
Revises: 
Create Date: 2025-07-09 20:44:25.472110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1195506c0e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('image_type',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('image_type',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
